// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("ImageProcessing")>]
[<assembly: AssemblyProductAttribute("ImageProcessing")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2017-03-17T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "b385af579477bb585016a6b5204121de4a485dac")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "ImageProcessing"

    [<Literal>]
    let AssemblyProduct = "ImageProcessing"

    [<Literal>]
    let AssemblyVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"

    [<Literal>]
    let AssemblyFileVersion = "0.1.0"

    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "b385af579477bb585016a6b5204121de4a485dac"
